platformName: Android
#模拟器
platformVersion: 5.1.1
deviceName: 127.0.0.1:62026

#mx4真机
#platformVersion: 8.0.0
#udid: HMKNW17916007980
#deviceName: 192.168.43.1:5555

appname: weixin706android1480.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True

appPackage: com.tencent.mm
appActivity: com.tencent.mm.ui.LauncherUI
ip: 127.0.0.1
port: 4723